exports.seed = knex =>
  knex('reviews').insert([
    {
      quietness: 2,
      wifi_speed: 1,
      close_late: 4,
      community: 5,
      accessibility: 5,
      description: 'Service was awesome',
      user_id: 1,
      location_id: 1,
    },
    {
      quietness: 3,
      wifi_speed: 4,
      close_late: 2,
      community: 1,
      accessibility: 1,
      description: 'Service was meh',
      user_id: 2,
      location_id: 2,
    },
    {
      quietness: 5,
      wifi_speed: 5,
      close_late: 1,
      community: 3,
      accessibility: 2,
      description: 'was kinda over there',
      user_id: 3,
      location_id: 3,
    },
    {
      quietness: 1,
      wifi_speed: 1,
      close_late: 2,
      community: 1,
      accessibility: 3,
      description: 'It definitely could have been better',
      user_id: 4,
      location_id: 4,
    },
    {
      quietness: 3,
      wifi_speed: 4,
      close_late: 4,
      community: 5,
      accessibility: 5,
      description: 'Great, great place to code!',
      user_id: 5,
      location_id: 5,
    },
  ]);
